from romeo_hydra.kernel.sigma_chameleon import (
    KernelConfig,
    KernelSigmaController,
    CoreState,
    MimeticSurfaceAdapter,
    EnvironmentSpectrum,
)
from romeo_hydra.kernel.cerebro_7219 import (
    CerebroResonador7219,
    ModulacionResonante7219,
    ANGLE_PENTAGONS_72,
    PRIME_ANCHOR_19,
)
from romeo_hydra.kernel.plam_quantum import (
    PLAMConfig,
    PLAMResult,
    PLAMQuantumWrapper,
    BifurcationMode,
    ContainmentStatus,
    plam_quantum_wrapper,
)
from romeo_hydra.kernel.dossier_math import (
    AXIOM_I,
    AXIOM_II,
    AXIOM_III,
    SigmaThresholds,
    DEFAULT_THRESHOLDS,
    double_well_potential,
    double_well_hessian_analytical,
    structural_potential_sigma,
    structural_hessian_sigma,
    balance_functional,
    HPRResult,
    HPREngine,
    numerical_jacobian,
    hessian_vector_product,
    kronecker_inverse_blocks,
    PPRHPhase,
    PPRHState,
    PPRHProtocol,
    validate_block_chain,
    make_block,
    DossierMathCore,
)

__all__ = [
    "KernelConfig",
    "KernelSigmaController",
    "CoreState",
    "MimeticSurfaceAdapter",
    "EnvironmentSpectrum",
    "CerebroResonador7219",
    "ModulacionResonante7219",
    "ANGLE_PENTAGONS_72",
    "PRIME_ANCHOR_19",
    # Anexo Q · Contención cuántica / P_LAM
    "PLAMConfig",
    "PLAMResult",
    "PLAMQuantumWrapper",
    "BifurcationMode",
    "ContainmentStatus",
    "plam_quantum_wrapper",
    # Dossier Matemático Supremo (RAEK-1.0-MX)
    "AXIOM_I",
    "AXIOM_II",
    "AXIOM_III",
    "SigmaThresholds",
    "DEFAULT_THRESHOLDS",
    "double_well_potential",
    "double_well_hessian_analytical",
    "structural_potential_sigma",
    "structural_hessian_sigma",
    "balance_functional",
    "HPRResult",
    "HPREngine",
    "numerical_jacobian",
    "hessian_vector_product",
    "kronecker_inverse_blocks",
    "PPRHPhase",
    "PPRHState",
    "PPRHProtocol",
    "validate_block_chain",
    "make_block",
    "DossierMathCore",
]
